### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by ghost** [retsimx/tlsr8266_mesh#1]
https://github.com/ivan64435/tlsr8266_programmer

**Comment by retsimx** [comment]
Can you please provide a test case? thank you

**Comment by ghost** [comment]
I'll try to make a video when I have time

**Comment by ghost** [comment]
the hardware part is connected according to the scheme, in the configuration section you need to select the FTDI device and click on the button connect to tlsr8266 if the connection did not happen, then you need to select the speed (this is very important, unfortunately it can float and cause desynchronization)

**Comment by retsimx** [comment]
But I've written a raspberry pi pico w application that does this for me using the swire interface. It's in https://github.com/retsimx/tlsr8266_mesh/blob/main/picow_swire/main.py

**Comment by ghost** [comment]
I don't have a raspberry pi, so I wrote a programmer for an FTDI chip, only virustotal says that my programmer is a virus, but this is typical for VB6 programs
